# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d7dce251274145259b8a6aa44c6142b730ab035d823092e0b18c57f3ed8693133c9ea9eb8f75b6ab548f9ae9d0ef5d6342cf2595117da233befc0ac2dca98e

test:
  secret_key_base: 4bb99c1a352bb2f5fcf97c6aede722fe155f80fbcb1096529766c7abd5963e698d64b1d992eaf52d71554a12345ac8ad05369ff3f04b6e67cc07e861cd601c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
